## Lucky Numbers in a Matrix

#### min in its row
#### max in its column

In [1]:
import numpy as np

In [2]:
array1 = np.array([[3,7,8],[9,11,13],[15,16,17]])
array1

array([[ 3,  7,  8],
       [ 9, 11, 13],
       [15, 16, 17]])

In [3]:
#output: 15

In [4]:
array2 = np.array([[1,10,4,2],[9,3,8,7],[15,16,17,12]])
array2

array([[ 1, 10,  4,  2],
       [ 9,  3,  8,  7],
       [15, 16, 17, 12]])

In [5]:
#output: 12

In [6]:
def lucky_number_matrix(array):
    result = []
    
    n = len(array[0])
    num_list = sum(array, [])
    
    for i in range(len(array)):
        x = min(array[i])
        j = array[i].index(x)
        y = max(num_list[j::n])
        
        if x == y:
            result.append(x)
            
    return result

In [7]:
x = [[3,7,8],[9,11,13],[15,16,17]]
y = [[1,10,4,2],[9,3,8,7],[15,16,17,12]]

print(lucky_number_matrix(x))
print(lucky_number_matrix(y))

[15]
[12]


## Find numbers with even number of digits

Input: nums = [12, 345, 2, 6, 7896]

Output: 2

In [8]:
def find_numbers(nums):
    even = 0
    for i in nums:
        if len(str(i)) % 2 == 0:
            even += 1
    return even

In [9]:
numbers = [12, 345, 2, 6, 7896]

In [10]:
find_numbers(numbers)

2

## How many smaller numbers are smaller than the current number?

input: [8, 1, 2, 2, 3]

output: [4, 0, 1, 1, 3]

In [11]:
def smaller_num_than_current(nums):
    new_list = []
    
    for i in nums:
        count = 0
        for j in nums:
            if i > j:
                count += 1
        new_list.append(count)
        
    return new_list

In [12]:
nums = [8, 1, 2, 2, 3]
smaller_num_than_current(nums)

[4, 0, 1, 1, 3]

## Move Zeroes 

Input: [0, 1, 0, 3, 12]

Output: [1, 3, 12, 0, 0]

In [13]:
def move_zeroes(nums):
    new_list = []
    for i in nums:
        if i == 0:
            nums.remove(i)
            new_list.append(i)
    
#     for j in new_list:
#         nums.append(new_list)
    
    return nums + new_list

In [14]:
nums = [0,1, 0, 3, 12]
move_zeroes(nums)

[1, 3, 12, 0, 0]

## Add Digits 

Input: 38

Output: 2 

Explanation: The process is like: 3 + 8 = 11, 1 + 1 = 2. 
             Since 2 has only one digit, return it.

In [15]:
def add_digits(number):
    
    while len(str(number)) > 1:
        number = sum(map(int, str(number)))
    
    return number

In [16]:
add_digits(38)

2

## Find Common Characters

Input: ["bella","label","roller"]

Output: ["e","l","l"]

...


Input: ["cool","lock","cook"]

Output: ["c","o"]


In [48]:
import random
import math

In [53]:
ds = ['Augustine', 'Peter', 'Ramy', 'Qili', 'Chris',
     'Celine', 'Tianmu', 'Xinhan', 'Coco', 'Meghna']

def data_science_teams(ds):
    random.shuffle(ds)
    num = int(len(ds)/2)
    team1 = ds[:num]
    team2 = ds[num:]
    
    return team1, team2

data_science_teams(ds)

(['Chris', 'Coco', 'Meghna', 'Ramy', 'Augustine'],
 ['Celine', 'Xinhan', 'Qili', 'Peter', 'Tianmu'])

### Input: groupSizes = [3,3,3,3,3,1,3]
### Output: [[5],[0,1,2],[3,4,6]]



### Explanation: 
### Other possible solutions are [[2,1,6],[5],[0,4,3]] and [[5],[0,6,2],[4,3,1]]

In [1]:
def groupThePeople(groupSizes):
    dic = {}
    for i,v in enumerate(groupSizes):
        if v in dic:
            dic[v].append(i)
        else:
            dic[v] = [i]
    res = []
    for size in dic:
        while len(dic[size]) >= size:
            res.append(dic[size][:size])
            del dic[size][:size]
    return res

## Sort Matrix Diagonally

In [ ]:
def diagonalSort(array):
    

In [40]:
import numpy as np

In [121]:
mat = np.array([[3,3,1,1],[2,2,1,2],[1,1,1,2]])

In [94]:
len(mat)

3

In [95]:
len(mat[0])

4

In [96]:
a , b = len(mat), len(mat[0])

In [150]:
mat

array([[3, 3, 1, 1],
       [2, 2, 1, 2],
       [1, 1, 1, 2]])

In [183]:
x[0:].diagonal(0) = mat[0:].diagonal(0)[::-1]

SyntaxError: can't assign to function call (<ipython-input-183-7a44942d0b4a>, line 1)

In [177]:
d = mat[0:].diagonal(0)[::-1]

In [170]:
mat[0:].diagonal(0)

array([3, 2, 1])

In [159]:
mat[1:].diagonal(1)[::-1]

array([1, 2])

In [144]:
mat[0:].diagonal(0)

array([3, 2, 1])

In [174]:
x = np.empty([3,4])
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [118]:
mat.diagonal(0)[::-1][0]

1

In [110]:
mat[1:].diagonal(2)

array([1, 2])

In [67]:
mat[1:]

array([[2, 2, 1, 2],
       [1, 1, 1, 2]])

array([ 1,  2,  3, 10, 11, 12])

## Letter Tile Possibilities

Input: "AAB"

Output: 8

Explanation: The possible sequences are "A", "B", "AA", "AB", "BA", "AAB", "ABA", "BAA".

In [9]:
def numTilePossibilities(tile):
    from itertools import permutations 
        
    lst = []
    for i in range(len(tile)):  
        lst.extend(set(permutations(tile, i + 1)))

    return len(lst)

In [10]:
tile = "AAB"

numTilePossibilities(tile)

8